In [2]:
import numpy as np
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a = np.floor(10*np.random.random((3,4)))
a.ravel()

array([ 1.,  8.,  8.,  5.,  7.,  9.,  5.,  5.,  5.,  5.,  8.,  6.])

In [5]:
a.shape = (6,2)
a

array([[ 1.,  8.],
       [ 8.,  5.],
       [ 7.,  9.],
       [ 5.,  5.],
       [ 5.,  5.],
       [ 8.,  6.]])

In [9]:
np.c_[[-1],[-2]]

array([[-1, -2]])

In [11]:
a=np.array([1,3,])
a

array([1, 3])

In [14]:
from numpy import newaxis
a[:,newaxis]

array([[1],
       [3]])

In [15]:
a[newaxis,:]

array([[1, 3]])

In [18]:
b=np.array([[1,2,3],
   [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b[:,newaxis]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [20]:
b[newaxis,:]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [21]:
a = np.array([4,2])
b = np.array([2,8])
np.hstack((a[:,newaxis],b[:,newaxis]))

array([[4, 2],
       [2, 8]])

In [25]:
a = np.floor(10*np.random.random((4,12)))
a

array([[ 1.,  5.,  0.,  9.,  8.,  2.,  7.,  1.,  6.,  1.,  5.,  6.],
       [ 8.,  9.,  5.,  8.,  6.,  5.,  1.,  0.,  3.,  3.,  4.,  5.],
       [ 1.,  9.,  3.,  0.,  1.,  7.,  9.,  0.,  2.,  0.,  4.,  0.],
       [ 6.,  8.,  6.,  1.,  9.,  6.,  8.,  5.,  6.,  7.,  7.,  8.]])

In [26]:
np.hsplit(a,3)

[array([[ 1.,  5.,  0.,  9.],
        [ 8.,  9.,  5.,  8.],
        [ 1.,  9.,  3.,  0.],
        [ 6.,  8.,  6.,  1.]]), array([[ 8.,  2.,  7.,  1.],
        [ 6.,  5.,  1.,  0.],
        [ 1.,  7.,  9.,  0.],
        [ 9.,  6.,  8.,  5.]]), array([[ 6.,  1.,  5.,  6.],
        [ 3.,  3.,  4.,  5.],
        [ 2.,  0.,  4.,  0.],
        [ 6.,  7.,  7.,  8.]])]

In [27]:
np.vsplit(a,2)

[array([[ 1.,  5.,  0.,  9.,  8.,  2.,  7.,  1.,  6.,  1.,  5.,  6.],
        [ 8.,  9.,  5.,  8.,  6.,  5.,  1.,  0.,  3.,  3.,  4.,  5.]]),
 array([[ 1.,  9.,  3.,  0.,  1.,  7.,  9.,  0.,  2.,  0.,  4.,  0.],
        [ 6.,  8.,  6.,  1.,  9.,  6.,  8.,  5.,  6.,  7.,  7.,  8.]])]

In [28]:
np.hsplit(a,(3,5))

[array([[ 1.,  5.,  0.],
        [ 8.,  9.,  5.],
        [ 1.,  9.,  3.],
        [ 6.,  8.,  6.]]), array([[ 9.,  8.],
        [ 8.,  6.],
        [ 0.,  1.],
        [ 1.,  9.]]), array([[ 2.,  7.,  1.,  6.,  1.,  5.,  6.],
        [ 5.,  1.,  0.,  3.,  3.,  4.,  5.],
        [ 7.,  9.,  0.,  2.,  0.,  4.,  0.],
        [ 6.,  8.,  5.,  6.,  7.,  7.,  8.]])]

In [24]:
np.hsplit(a,3)

[array([[ 4.,  5.,  6.,  1.],
        [ 3.,  8.,  5.,  5.]]), array([[ 0.,  5.,  5.,  8.],
        [ 5.,  4.,  9.,  2.]]), array([[ 4.,  1.,  2.,  6.],
        [ 8.,  9.,  9.,  1.]])]

In [ ]:
np.