In [56]:
import numpy as np
from pyquaternion import Quaternion

def quatRotateVecDiff(q, v):
    # dq
    dq = np.hstack([np.identity(4), np.zeros((4,3))])
    # dr
    aux = np.vstack([np.zeros((1,3)), np.identity(3)])
    dr = np.hstack([np.zeros((4,4)), aux])
    # q_times_r && dq_times_r
    r_0 = np.insert(v, 0, 0)
    q_times_r = (Quaternion(q) * Quaternion(r_0)).q
    dq_times_r = quatProductDiff(q, r_0)
    # q_conj && dq_conj
    q_conj = Quaternion(q).conjugate.q
    dq_conj = quatConjugateDiff(q)
    # r_rot, dr_rot
    r_rot = (Quaternion(q_times_r) * Quaternion(q_conj)).q
    dr_rot = quatProductDiff(q_times_r, q_conj)
    # dr_rot i.e., res
    aux = np.vstack([dq, dr])
    aux = np.dot(dq_times_r, aux)
    aux = np.vstack([aux, np.dot(dq_conj, dq)])
    dr_rot = np.dot(dr_rot, aux)
    res = dr_rot[1:]
    return res

def quatProductDiff(lhs, rhs):
    # w1
    w1 = lhs[0]
    # w2
    w2 = rhs[0]
    # v1
    v1 = lhs[1:]
    # v2
    v2 = rhs[1:]
    
    # dq1
    dq1 = np.hstack([np.identity(4), np.zeros([4,4])])
    # dq2
    dq2 = np.hstack([np.zeros([4,4]), np.identity(4)])
    # dw1
    dw1 = dq1[0]
    # dw2
    dw2 = dq2[0]
    # dv1
    dv1 = dq1[1:]
    # dv2
    dv2 = dq2[1:]
    
    # dw3
    dw3 = w2*dw1 + w1*dw2 - np.dot(v2, dv1) - np.dot(v1, dv2)
    # dv3
    dv3 = dcross(v1, v2, dv1, dv2) + np.dot(v2, dw1) + np.dot(w1, dv2) + np.dot(v1, dw2) + np.dot(w2, dv1)
    
    # dq3
    dq3 = np.vstack([dw3, dv3])

def quatConjugateDiff(q):
    pass

q = np.array([0,1,0,0])
v = np.array([1,2,3])
#quatRotateVecDiff(q,v)
print np.zeros([4,3])

#A = np.array([[1,2,3], [4,5,6]])
B = np.ones([1, 8])
x = np.ones(3).reshape(3,1)
print x.reshape(3,1)
print B
print np.dot(x,B)
#print A * B

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.]
 [ 1.]
 [ 1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]]
